### ISSUE TITLE
Exporting twig for extending its functionality

### ISSUE THREAD

**Issue by mgrsskls** [larowlan/twig-testing-library#1]
Hey,

thank you for that cool library! Exporting twig would be really helpful for us, as we use custom functions in our templates. If `twig-testing-library` exported it, we could something like the following:

```
import { render, twig } from "twig-testing-library";

twig.extendFunction("custom_function", () => ...);

describe(...);
```

Thanks,
Michael

**Comment by larowlan** [comment]
Nice idea, should be simple to add. Leave it with me
