### ISSUE TITLE
Support for i18n extension

### ISSUE THREAD

**Issue by BoomerIsSpartacus** [larowlan/twig-testing-library#12]
Hi, 

Would it be possible to allow for the translation extension in this library? At the moment wherever there is a {% trans %}{% endtrans %} block the test complains that it is unable to parse 'trans'. 

If I am missing something and it is already supported, please point me in the right direction!

**Comment by larowlan** [comment]
https://github.com/twigjs/twig.js/wiki/Extending-twig.js has notes on extending Twig.js with custom tags

Trans isn't listed in supported extensions https://github.com/twigjs/twig.js/wiki/Implementation-Notes

It looks like the Drupal twig extension includes trans - https://www.npmjs.com/package/twig-drupal-filters

So you can likely install that package, and extend Twig with that.

**Comment by BoomerIsSpartacus** [comment]
If you extend using the Drupal twig, wouldn't that mean that you will no longer be using the twig-testing-library to render the twig template? I can stress that the trans blocks are working in the application, I am just struggling to render it in testing.

**Comment by larowlan** [comment]
The twig object is returned by twig testing library, you should be able to decorate it with the Drupal filters

**Comment by BoomerIsSpartacus** [comment]
So are you suggesting something like this before calling the render function from the twig-testing-library:
`import addDrupalExtensions from 'drupal-twig-extensions';
addDrupalExtensions(Twig);`  ?

**Comment by larowlan** [comment]
Yep, see the example in the [twig testing library readme](https://github.com/larowlan/twig-testing-library) (search for Twig.extendFilter)

**Comment by BoomerIsSpartacus** [comment]
So it actually did not work because trans is set as a tag as part of twig files, not filter or function. So extending directly on Twig did the job. Thanks for the discussion and for coming back to me.
