### ISSUE TITLE
Support for Drupal Twig Extensions

### ISSUE THREAD

**Issue by zaidaldabbagh** [larowlan/twig-testing-library#13]
The current render function doesn't appear to support/allow use of Drupal's Twig extensions like `clean_class` or `file_url`. Error thrown: `TwigException: Unable to find filter clean_class`. The same applies to use of our custom Twig Extensions. Currently having to use `Twig.extendFilter('clean_class', (value) => value);`.

**Comment by larowlan** [comment]
You should be able to use https://github.com/kalamuna/twig-drupal-filters

**Comment by zaidaldabbagh** [comment]
Thank you so much @larowlan, yes indeed that did fix the handling of Drupal's Twig filters.
This is what it looks like now ...
```
import { render, Twig } from 'twig-testing-library';
import twigDrupal from 'twig-drupal-filters';

// Add the filters to Drupal.
twigDrupal(Twig);
```

That said, I'm assuming that we'd need to stub any future custom Twig extensions in JS and load those in the same way we load 'twig-drupal-filters'.

**Comment by larowlan** [comment]
Yep, that's the way

I'd create a wrapper function and use that in your tests to avoid having to cop/update it everywhere
