### ISSUE TITLE
Unable to override template variables that are set in template

### ISSUE THREAD

**Issue by zaidaldabbagh** [larowlan/twig-testing-library#14]
We dynamically set numerous variables in template using {% set title = 'New title' %} ... Therefore I'm unable to pass in the `title` variable in the `render` function, as that's overridden by the set statement inside the Twig template. One way I'm able to override this, is to pass in a `mocked: true` prop, that I can then use inside my twig template before setting my variables with `{% set title = 'New title' %} ` which works. Is there a nicer way around this? Many thanks in advance.

```
{% if not mocked %}
  {% set var_1 = '1234' %}
  {% set var_2 = '1234' %}
{% endif %}
```

**Comment by larowlan** [comment]
I'm not sure what you're actually testing if you've got a hard-coded title in your template.
ie. what is the point of passing that property, you're not testing a real-world scenario.

But failing that, you can use twig's default filter in your template

`[% set title = title|default('New title') %}`

So if you pass a title, it is used, but if not it falls back to the default

**Comment by zaidaldabbagh** [comment]
Apologies I think I gave a bad example ... we managed to resolve this using Twig's default filter, feel free to close this.
This is how we've used it ... 
```
{% set audio_file_mime = audio_file.filemime[0].value|default('audio/mpeg') %}
{% set audio_file_name = audio_file.getFilename()|default('Sample-Audio-File.mp3') %}
{% set audio_file_extension = macros.mimeToExtension(audio_file_mime, audio_file_name) %}
```
