### ISSUE TITLE
Twig template aliases and test coverage reports. 

### ISSUE THREAD

**Issue by wrux** [larowlan/twig-testing-library#3]
I have 2 questions:

1. My Twig templates includes aliased file paths (so something like `{% include '@atoms/button/button.twig' %}` for example), but I cannot seem to get these working in Jest. I can see that you can parse in an object of the namespaces when using `render()` but is it possible to define the namespaces once for the whole project?

2. Is it possible to include Twig templates in the test coverage? I have defined the paths correctly in `collectCoverageFrom` but it seems like Jest only lists JS files in the coverage reports. It probably seems redundant, but it would be nice to see which components have tests

**Comment by larowlan** [comment]
Re 2, I don't think so, the twig files are parsed, but not executed as JavaScript.

Re 1, that is definitely supported. The third argument to the `render` function accepts a map of namespace to directory entries. Eg. the docs on the project page has this:

```JavaScript
    // Rendering is async, so you need to use await.
    const { container, getByText } = await render(
    // Path to twig template.
    'accordion.twig',
    // Template variables/context. 
    {
      title: 'Accordion title',
      open: true,
    }, 
    // Namespace support
    {
      'my_namespace': './some/path'
    });

```

In that scenario, you'd replace 'my_namespace' with 'atoms' and './some/path' with the path to atoms.

Hope that helps

**Comment by wrux** [comment]
@larowlan I have been doing this in my tests, it will be the same 4 namespaces getting parsed into the render function. It would be nice if we can configure some application wide namespaces once

**Comment by larowlan** [comment]
In that scenario, I've just been declaring them as a constant separately and using that in all the scenarios, but I see your point.

Would accept a PR with the option to set that once
